### ISSUE TITLE
Channel restrictions (+i mode?)

### ISSUE THREAD

**Issue by lol768** [Chatterbox/Chatterbox#10]

**Comment by jkcclemens** [comment]
To be done in "IRC-like channels" hook, eventually.

**Comment by lol768** [comment]
Channel bans would be cool too

**Comment by cindyker** [comment]
and Channel mutes are definitely needed if you don't have them already.

**Comment by gdude2002** [comment]
What merit would a channel mute have over a channel ban? I can see a global mute being useful, but I'm not sure about a channel mute

**Comment by cindyker** [comment]
I use channel mutes all the time, it allows me to get a semi annoying person's attention about their chat misbehavior. Allowing them to talk in some less popular channels only. Mute lets them continue to see the chat, just not participate.

**Comment by jkcclemens** [comment]
I have the following modes:
- ```i``` – Invite-only
- ```b``` – Ban (one arg, either name or UUID, autodetects and converts to UUID if necessary)
- ```m``` – Mute (one arg, same as above)

Suggestions for more, if necessary?

**Comment by WizardCM** [comment]
None that I can think of, those sound good. Would channels also have a `mute list` command (or something in-game to show the channel's options and would list who's banned/muted?

**Comment by jkcclemens** [comment]
It's conceivable!

**Comment by lol768** [comment]
> m – Mute (one arg, same as above)

Can I convince you to make this become `q` or have an alias?

**Comment by gdude2002** [comment]
> Can I convince you to make this become q or have an alias?

Technically it should be `+b ~q:whatever` or `+b $q:whatever`, but these aren't IRC, just IRC-like.

Maybe an alias, but +m makes more sense for most users.

**Comment by jkcclemens** [comment]
Adding a cool guy todo list, since I'm basically really close to done with this.

- [ ] Fix kicks
- [ ] Save modes to a file
- [ ] Save player channels to a file
- [ ] Make sure channels are loaded for memberships
- [ ] /knock

**Comment by jkcclemens** [comment]
This is completed in the hooks repository. Locking this issue. If issues arise, they should be made in the hooks repository.
