### ISSUE TITLE
Fully update the wiki

### ISSUE THREAD

**Issue by jkcclemens** [Chatterbox/Chatterbox#12]
# Content
- [x] Channels
  - [x] What they are
  - [x] Master channel
  - [x] Formatting (explained in `Channel configuration`, but needs more in-depth coverage)
  - [X] @-tags
- [x] Rythm
- [x] Titles
  - [x] How to use
- [x] Messaging
- [x] Commands and permissions
  - [x] /chatterbox
  - [x] /channel
  - [x] /join
  - [x] /leave
  - [x] /reload
  - [x] /say
  - [x] /action
  - [x] /message
  - [x] /reply
- [x] API
  - [x] Player API
  - [x] Message API
  - [x] Channel API
  - [x] Rythm API
  - [x] Title API
  - [x] Messaging API
- [x] General
  - [x] Message pipeline (this is explained in `FAQ`, but adding information on how to add your own seems important. Ties in with API)
    - [x] Stages
- [x] Localization
- [x] Events
  - [x] ChannelCreateEvent
  - [x] ChannelJoinEvent
  - [x] ChannelLeaveEvent
  - [x] ChannelPreMessageEvent
  - [x] ChannelPostMessageEvent
- [x] Hooks

# Niceties
- [x] Sidebar for navigation (in progress; can only be finished when the above is)

Footer? Probably not necessary.

# Notes
Should have some sort of index, unless we can already search wikis.
- [x] Index

**Comment by lol768** [comment]
@jkcclemens I take it the example.com issue is part of this?

**Comment by jkcclemens** [comment]
Oh christ. Forgot about those.

**Comment by jkcclemens** [comment]
I believe that I've covered most things. It may require updating from people that spot errors or things I've missed.

**Comment by gdude2002** [comment]
MIssing..
* Docs about providing additional variables to Rythm (Probably under hooks)
* Short developers' guide to supporting Chatterbox in their plugin
* Advanced template stuff, such as how templates that are parsed for each recipient work

Probably forgot some other stuff as well
