### ISSUE TITLE
[Request] /message, /tell, etc

### ISSUE THREAD

**Issue by turt2live** [Chatterbox/Chatterbox#24]
The "recipient" channel seems perfect for this, however the plugin makes no attempt at overriding these commands (let alone implementing them).

**Comment by gdude2002** [comment]
I think I suggested this at some point, probably going to be low-priority though.

**Comment by turt2live** [comment]
Understood, just was slightly surprised it wasn't implemented is all.

**Comment by jkcclemens** [comment]
I guess the question is in the implementation. Should there be a special channel for messages, which contains a player and recipient variable, using recipient sections? Could send all messages through that.

Feedback? Suggestions? Pizza?

**Comment by turt2live** [comment]
From a user standpoint, I'd like to see a consistent format used for all messages. How it works may be dependent on how the user expects it to work.

As for ideas on operation... (examples are samples of potential conversation)

Possible Option 1:
```
turt2live > /msg jkcclemens Hey there!
jkcclemens > @r hey
turt2live > @r how are you?
...
```

Possible Option 2:
```
turt2live > @m:jkcclemens Hey there!
turt2live > @m:gdude What's up?
jkclemens > @r Hey
turt2live > @m:jkcclemens How are you?
gdude > @r nothing much, you?
turt2live > @m:gdude Nothing much.
```

Possible Option 3:
Combination of 1 and 2.

*Note*: It would be expected that `@m:jkc<tab>` would work as expected (autocompleted names).

**Comment by turt2live** [comment]
For administration purposes, the format already specified (`[from -> to] message`) would be ideal, however a default format for received/sent messages may be something like these:

`[from] message`
`[>> from] message`
`[to] message`
`[<< to] message`

**Comment by turt2live** [comment]
That being said, administration/monitoring may be out of scope for now to be honest. It would be useful for paranoid server admins (permission-based channel that could be joined by approrpriate staff to monitor all chatter) or to just be logged in the console for retrieval later on.

**Comment by jkcclemens** [comment]
Wow. Well, I really meant for formatting... we could have a "channel" that defines a format used for messages, like
```yaml
format:
  text: [@(player.getName()) -> @(chatterbox.recipient("name"))] @(message)
  recipient:
    name: |
          @(recipient.getName())
