### ISSUE TITLE
Exception thrown with `/chatterbox reload`

### ISSUE THREAD

**Issue by turt2live** [Chatterbox/Chatterbox#27]
[Stacktrace](http://i.turt2live.com/cB4v.txt) | [Configuration](http://i.turt2live.com/VvnG.txt)

**Comment by turt2live** [comment]
Note: applies to shutdown as well (`/stop`)

**Comment by jkcclemens** [comment]
This is literally the lowest priority of ANY of these issues. I do not care.

**Comment by turt2live** [comment]
It does not appear to break functionality, it's just annoying. Cannot reproduce on non-Windows systems.

Tested with Windows 8.1.

**Comment by jkcclemens** [comment]
Before you reopen, please consider that I have absolutely no idea how to fix this. Windows is the worst. As far as I can tell, I have nothing actually using that jar, except for ClassLoaders, which I can't really wrangle with. This doesn't hurt anything, really, so we can just let server owners know to restart their servers if they need the Vault hook updated.
