### ISSUE TITLE
[Request] "on-the-fly" channels

### ISSUE THREAD

**Issue by turt2live** [Chatterbox/Chatterbox#31]
I couldn't find anything that indicates this is supported, but if it does please direct me to said documentation.

-----

An "on-the-fly" channel would be something like party/group chat for users. Ideally these could be optionally password protected or invite-only but that may be out of scope. The channels could have a default configurable limit of players (for example, 5) and the channel could be accessed via `@party` or `@<custom name>`. 

A "party" chat would be something where you are invited in as a group. You cannot be in multiple parties. Think of this like a faction chat with just a few friends.

A "custom channel" would be something for users to create whenever to have conversations with friends. These could be invite-only, password protected, or free to browse. Implementation is up to the developer(s).

------

Note: I don't expect this to be accepted. Just thought it would be neat :3

**Comment by jkcclemens** [comment]
See #10.

**Comment by turt2live** [comment]
#10 discuses modes of channels, not party chat or player-created channels.

**Comment by jkcclemens** [comment]
How should the format of a player-created channel be set?

**Comment by turt2live** [comment]
Define a format in the config for it? Kinda like "master" or something.

**Comment by jkcclemens** [comment]
That's what I was thinking. Players have no control over it, then?

**Comment by turt2live** [comment]
Ideally, yea: no control. Overkill would be a player could at most select from a set of formats, but nothing more than that (formats defined by server administrator(s))

**Comment by jkcclemens** [comment]
Including this in #10, as the IRC Channels hook.

As a note, I'll need to make a `/create <tag, no spaces> <name, spaces allowed>` command

**Comment by jkcclemens** [comment]
This was added in #10. Locking for the same reason.
