### ISSUE TITLE
RythmEngine.render() method do NOT need to be synchronized

### ISSUE THREAD

**Issue by greenlaw110** [Chatterbox/Chatterbox#32]
I found `RythmEngine. render()` method was synchronized in  https://github.com/Chatterbox/Chatterbox/blob/master/modules/Chatterbox/src/main/java/works/chatterbox/chatterbox/api/rythm/RythmAPI.java source code, actually this is not needed, neither it is encouraged as it will slow down your system unnecessarily. Keep in mind that `RythmEngine.render()` method is thread safe because it always clone an new `ITemplate` instance upon calling this method

**Comment by jkcclemens** [comment]
Huh. I thought it wasn't thread-safe for some reason. I'll fix that when I try implementing findResource.
