### ISSUE TITLE
Message trimming not perfect

### ISSUE THREAD

**Issue by turt2live** [Chatterbox/Chatterbox#35]
On a de-opped player the following scenarios were tested with the respective results:

(messages are `quoted like this` for readability)

 | Message Sent | Expected Result | Actual Result | Notes
------------- | ------------- | ------------- | ------------- | -------------
 ![a](http://i.turt2live.com/JGuP.png) | `&aTest` | `Test` | `Test` |
 ![a](http://i.turt2live.com/tpdU.png) | `&a Test` | `Test` | ` Test` | Extra space at start of result
 ![a](http://i.turt2live.com/JGuP.png) | `&aT&ae&as&at` | `Test` | `Test` |
 ![a](http://i.turt2live.com/JGuP.png) | `&aT &ae&as &at` | `T es t` | `T es t` |
 ![a](http://i.turt2live.com/JGuP.png) | `&a&a` | [no message] | [no message] |
 ![a](http://i.turt2live.com/tpdU.png) | `&a &a` | [no message] | ` ` | Entire message was 1 space
 ![a](http://i.turt2live.com/JGuP.png) | `Test @(invalid)` | `Test @(invalid)` | `Test @(invalid)` |

Also tried a JSON message, but GitHub does not like the formatting here. It worked as expected (json returned back to user without modifying the output)

**Comment by jkcclemens** [comment]
To be clear, you are expecting only the very beginning and very end of messages to be cleared of leading and trailing spaces, respectively, correct?

**Comment by turt2live** [comment]
Yes, which would mean that a non-op person sending `&a &a` would not actually send anything (just like if they sent `&a&a`)

**Comment by jkcclemens** [comment]
`&a Something    &a &bHello  &a ` -> `Something     Hello`?

**Comment by turt2live** [comment]
`Something  Hello` (2 spaces between words). 

Honestly the result of `stripColor(message).trim()` should be fine

**Comment by jkcclemens** [comment]
Closed in beecc87.
