### ISSUE TITLE
Nasty exceptions left in log when a user provides an invalid format

### ISSUE THREAD

**Issue by turt2live** [Chatterbox/Chatterbox#4]
Yes, it's a failure. But we don't need to crush the user with this amount of detail. A simple "your format is invalid" message is more than enough information for the user.

[Stack Trace](http://i.turt2live.com/XqEI.txt)

Format used:
`@(player.getNsage)`

What the user sees: 
![image](https://cloud.githubusercontent.com/assets/1190097/7741991/3d5a7612-ff45-11e4-9f94-7fb3c2162c53.png)

**Comment by jkcclemens** [comment]
I am sad to say that this cannot be fixed without making a dramatic change to the way that Rythm works. As such, I must mark it as closed.

**Comment by turt2live** [comment]
Hopefully it can be looked at in the future with the help of nagging the Rythm people.
