### ISSUE TITLE
Backslashes entered into chat are treated as escape characters

### ISSUE THREAD

**Issue by gdude2002** [Chatterbox/Chatterbox#40]
![](http://i.imgur.com/v5ZeyE7.jpg)

**Comment by jkcclemens** [comment]
This is intended.

**Comment by gdude2002** [comment]
This is pretty awful, lol. It's confused everyone that's used it. Should be an option.

**Comment by gdude2002** [comment]
Still unsure what this is for \o/

**Comment by turt2live** [comment]
![reasons](http://i.turt2live.com/ufMe.jpg)

**Comment by bendem** [comment]
For reference, these should check if the character after needs escaping:
https://github.com/Chatterbox/Chatterbox/blob/f6a3bef063a8c47e08f7577355ce999515a3733b/modules/Chatterbox/src/main/java/works/chatterbox/chatterbox/api/impl/message/DefaultMessageAPI.java#L61
https://github.com/Chatterbox/Chatterbox/blob/f6a3bef063a8c47e08f7577355ce999515a3733b/modules/Chatterbox/src/main/java/works/chatterbox/chatterbox/api/impl/message/DefaultMessageAPI.java#L86

**Comment by kashike** [comment]
Users should not be forced to escape input imo.
