### ISSUE TITLE
Percent signs are doubled

### ISSUE THREAD

**Issue by gdude2002** [Chatterbox/Chatterbox#42]
`%` -> `%%`. wat?

**Comment by gdude2002** [comment]
This doesn't seem to happen for `/say`, however

**Comment by jkcclemens** [comment]
I have to say, @gdude2002, you are probably the worst issue reporter outside of me making issues for myself. When, where, and how? Was it in a JSON channel, a normal channel, a recipient channel, etc.

It doesn't happen in `/say` because `/say` doesn't go through the normal message pipeline.

**Comment by gdude2002** [comment]
It was in the default channel. When sending a message containing a `%` in it.
